main: thirtyvirus.challenge.ChallengePlugin
version: 1.0
name: ChallengePlugin
api-version: 1.13

commands:
  challenge:
    description: Main command for ChallengePlugin. Use /template help for more info
permissions:
  challenge.user:
    description: Allows player to use the plugin's user features
    default: true
  challenge.admin:
    description: Allows player to use the plugin's admin features
    default: op