main: thirtyvirus.template.ChallengePlugin
version: 1.0
name: ChallengePlugin
api-version: 1.13

commands:
  template:
    description: Main command for ChallengePlugin. Use /template help for more info
permissions:
  template.user:
    description: Allows player to use the plugin's user features
    default: true
  template.admin:
    description: Allows player to use the plugin's admin features
    default: op